sudo: false
language: node_js
notifications:
  disabled: true

# Cache the 3rd-party packages. From https://blog.travis-ci.com/2016-11-21-travis-ci-now-supports-yarn
cache:
  yarn: true
  directories:
    - node_modules

script: npm test
after_success: bash <(curl -s https://codecov.io/bash)
