sudo: false
language: node_js
notifications:
  disabled: true

# Cache the 3rd-party packages. From https://blog.travis-ci.com/2016-11-21-travis-ci-now-supports-yarn
cache:
  yarn: true
  directories:
    - node_modules

# https://github.com/greenkeeperio/greenkeeper-lockfile#yarn
before_install: yarn global add greenkeeper-lockfile@1
before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload

script: npm test
after_success: bash <(curl -s https://codecov.io/bash)
